name: 'Random-Quote-Action'
description: 'Puts a random Quote in your README'
author: SpiderMath

inputs:
  QUOTE_FONT_SIZE:
    description: 'The size of the quote, lies between 1 to 6, 1 being the largest'
    default: 3
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'