name: 'Random-Quote-Action'
description: 'Puts a random Quote in your README'
author: SpiderMath

inputs:
  GH_USERNAME:
    description: 'Your GitHub Username'
    default: ${{github.repository_owner}}
    required: false
  COMMIT_MESSAGE:
    description: 'The commit message, which you want to be displayed on update'
    default: ':zap: Updated the README with a new quote'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'