name: 'Random-Programming-Quote-Action'
description: 'Puts a random programming Quote in your README'
author: SpiderMath

inputs:
  QUOTE_FONT_SIZE:
    description: 'The size of the quote, lies between 1 to 6, 1 being the largest'
    default: 3
    required: false
  COMMIT_MESSAGE:
    description: 'The message which you want the bot to send on commit'
    default: 'Updated the README with a new Programming Quote 💻'
    required: false
  GH_USERNAME:
    description: 'The bot name which you want the Action to commit quote with'
    default: 'Readme Programmer'
    required: false
  ITALICS:
    description: 'Whether you want the text to be italicized'
    required: false
    default: true
  BLOCKQUOTES:
    description: 'Whether you want your quote to be in a blockquote'
    required: false
    default: true

runs:
  using: 'node12'
  main: 'dist/index.js'