name: Test

on:
  schedule: 
    - cron: '0/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Tests Random-Quote-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: spidermath/random-quote-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MESSAGE: 'I did work :zap:'
          GH_USERNAME: 'Quote Bot'