name: Test

on:
  schedule: 
    - cron: '0/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Generate build and check code formatting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: spidermath/random-quote-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}